---
rule-providers:
  Whatsapp:
    type: file
    behavior: domain
    path: "./rule_provider/whatsapp.yaml"
  Apex:
    type: file
    behavior: classical
    path: "./rule_provider/apex.yaml"
  COCCR:
    type: file
    behavior: classical
    path: "./rule_provider/coccr.yaml"
  COD:
    type: file
    behavior: classical
    path: "./rule_provider/cod.yaml"
  FIFA:
    type: file
    behavior: classical
    path: "./rule_provider/fifa.yaml"
  FF:
    type: file
    behavior: classical
    path: "./rule_provider/freefire.yaml"
  GenshinImpact:
    type: file
    behavior: classical
    path: "./rule_provider/genshinimpact.yaml"
  Mihoyo:
    type: file
    behavior: classical
    path: "./rule_provider/miHoYo.yaml"
  MLBB:
    type: file
    behavior: classical
    path: "./rule_provider/mlbb.yaml"
  PUBGM:
    type: file
    behavior: classical
    path: "./rule_provider/pubgm.yaml"
  TOF:
    type: file
    behavior: classical
    path: "./rule_provider/tof.yaml"
  Speedtest:
    type: file
    behavior: classical
    path: "./rule_provider/speedtest.yaml"
  Port-TCP:
    type: file
    behavior: classical
    path: "./rule_provider/PortTCP.yaml"
  Port-UDP:
    type: file
    behavior: classical
    path: "./rule_provider/PortUDP.yaml"
  PS:
    type: file
    behavior: domain
    path: "./rule_provider/playstore.yaml"
  Sosmed:
    type: file
    behavior: domain
    path: "./rule_provider/sosmed.yaml"
  Telegramcidr:
    type: file
    behavior: ipcidr
    path: "./rule_provider/telegramcidr.yaml"
  Olshop:
    type: file
    behavior: domain
    path: "./rule_provider/olshop.yaml"
  Stream:
    type: file
    behavior: domain
    path: "./rule_provider/stream.yaml"
  Id.only:
    type: file
    behavior: domain
    path: "./rule_provider/idonly.yaml"
  YouTube:
    type: file
    behavior: domain
    path: "./rule_provider/youtube.yaml"
  Banking:
    type: http
    behavior: domain
    path: "./rule_provider/banking.yaml"
  Zerotier:
    type: file
    behavior: classical
    path: "./rule_provider/zerotier.yaml"
  Personalads:
    type: file
    behavior: classical
    path: "./rule_provider/adblock.yaml"
  18+:
    type: file
    behavior: domain
    path: "./rule_provider/18+.yaml"
  Nsfw:
    type: file
    behavior: domain
    path: "./rule_provider/nsfw.yaml"
proxy-providers:
  ID:
    type: file
    path: "./proxy_provider/id.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 99
  SG:
    type: file
    path: "./proxy_provider/sg.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 99
proxy-groups:
- name: Internet
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - Server-ID
  - Server-SG
  - LoadBalance
  - Manual
- name: Server-ID
  type: fallback
  disable-udp: false
  use:
  - ID
  url: http://www.gstatic.com/generate_204
  interval: '360'
- name: Server-SG
  type: fallback
  disable-udp: false
  use:
  - SG
  url: http://www.gstatic.com/generate_204
  interval: '360'
- name: LoadBalance
  type: load-balance
  strategy: round-robin
  disable-udp: false
  proxies:
  - Server-ID
  - Server-SG
  url: http://www.gstatic.com/generate_204
  interval: '360'
- name: Manual
  type: select
  disable-udp: false
  use:
  - ID
  - SG
- name: M-Banking
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - Manual
  - Server-ID
  - Server-SG
- name: OL-Shop
  type: select
  disable-udp: false
  proxies:
  - Manual
  - Server-ID
  - Server-SG
  - DIRECT
  - REJECT
- name: WA
  type: select
  disable-udp: false
  proxies:
  - Manual
  - Server-ID
  - Server-SG
  - DIRECT
  - REJECT
- name: PlayStore
  type: select
  disable-udp: false
  proxies:
  - Manual
  - Server-ID
  - Server-SG
- name: SpeedTest
  type: select
  disable-udp: false
  use:
  - ID
  - SG
- name: Sosmed
  type: select
  disable-udp: false
  proxies:
  - Manual
  - Server-ID
  - Server-SG
  - DIRECT
  - REJECT
- name: Gaming
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - REJECT
  - Manual
- name: Youtube
  type: select
  disable-udp: false
  proxies:
  - Server-ID
  - Server-SG
  - LoadBalance
  - DIRECT
  - REJECT
- name: Indo Only
  type: select
  disable-udp: false
  proxies:
  - Server-ID
  - DIRECT
  - REJECT
- name: Streaming
  type: select
  disable-udp: false
  proxies:
  - Server-ID
  - Server-SG
  - LoadBalance
  - DIRECT
  - REJECT
- name: Zerotier.com
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - Internet
- name: AdBlock
  type: select
  disable-udp: false
  proxies:
  - Internet
  - DIRECT
  - REJECT
- name: 18+
  type: select
  disable-udp: false
  proxies:
  - Internet
  - DIRECT
  - REJECT
- name: PortTCP
  type: select
  disable-udp: false
  proxies:
  - Manual
  - DIRECT
  - REJECT
- name: PortUDP
  type: select
  disable-udp: false
  proxies:
  - Manual
  - DIRECT
  - REJECT
dns:
  nameserver:
  - dhcp://"eth1"
  - 192.168.8.1
  - 8.8.8.8
  - 8.8.4.4
  - tls://dns.google
  enable: true
  ipv6: false
  2enhanced-mode: fake-ip
  listen: 0.0.0.0:7874
  fake-ip-filter:
  - "+.*"
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - msftconnecttest.com
  - msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.srv.nintendo.net"
  - "*.n.n.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.*.microsoft.com
  - "*.*.xboxlive.com"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*.*.*"
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.ff14.sdo.com"
  - ff.dorado.sdo.com
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
  - "+.dns.google"
  default-nameserver:
  - 192.168.9.1
  - 192.168.8.1
  - 8.8.8.8
  - 8.8.4.4
  - 192.168.42.129
  enhanced-mode: redir-host
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: lunac3
bind-address: "*"
unified-delay: true
external-ui: "/usr/share/openclash/ui"
ipv6: false
profile:
  store-selected: true
  store-fake-ip: true
rules:
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- DST-PORT,3478,WA
- DST-PORT,4244,WA
- DST-PORT,53,WA
- DST-PORT,40020,WA
- DST-PORT,57923,WA
- RULE-SET,Apex,Gaming
- RULE-SET,COCCR,Gaming
- RULE-SET,COD,Gaming
- RULE-SET,FIFA,Gaming
- RULE-SET,FF,Gaming
- RULE-SET,GenshinImpact,Gaming
- RULE-SET,Mihoyo,Gaming
- RULE-SET,MLBB,Gaming
- RULE-SET,PUBGM,Gaming
- RULE-SET,TOF,Gaming
- RULE-SET,Speedtest,SpeedTest
- RULE-SET,PS,PlayStore
- RULE-SET,Port-TCP,PortTCP
- RULE-SET,Port-UDP,PortUDP
- RULE-SET,Banking,M-Banking
- RULE-SET,Whatsapp,WA
- RULE-SET,Sosmed,Sosmed
- RULE-SET,Telegramcidr,Sosmed
- RULE-SET,Olshop,OL-Shop
- RULE-SET,YouTube,Youtube
- RULE-SET,Id.only,Indo Only
- RULE-SET,Stream,Streaming
- RULE-SET,Zerotier,Zerotier.com
- RULE-SET,Personalads,AdBlock
- RULE-SET,18+,18+
- RULE-SET,Nsfw,18+
- MATCH,Internet
geodata-mode: false
geodata-loader: memconservative
tcp-concurrent: true
sniffer:
  enable: true
  sniffing:
  - tls
  - http
  ForceDnsMapping: true
  ParsePureIp: true
authentication:
- Clash:oHeRh67o
